# Site settings
title: LeuisKen的小屋
email: leuisken@gmail.com
description: >
  我现在生活在成都，目前就读于电子科技大学软件工程专业，将来希望去北京从事Web开发相关工作
  热衷于Web开发技术，也热衷于分享交流，希望能和大家一起共同成长
baseurl: ""
url: ""

#static images

#github source
local_url: "/assets/images"
static_url: "/assets/images"

#pagination
paginate: 5
paginate_path: "page:num"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
exclude: [node_modules, .tmp, Gruntfile.js, _config, package.json, articles.raw]

# default Front matter
defaults:
  -
    scope:
      path: pages
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      release: true
